### PR TITLE
Fixing bug when an attribute is missing

### PR DESCRIPTION
**Pull request by nicolas-chaulet**

### CODE REVIEW

**Review by humanpose1 — CHANGES_REQUESTED** [review]
There is a problem here. 
When I execute this code:
```python
from torch_geometric.data import Data
data = Data()
print(hasattr(data, "norm"))
```
I obtain `True`. because like `pos` and `x` it's set to `None` by default.

**Comment by nicolas-chaulet** [comment]
Ok, that's probably some difference in version of pytorch geometric or pytorch. what about `getattr(data,"norm", None)`?

**Comment by humanpose1** [comment]
```python
print(getattr(data,"norm", None))
```
The result is `None`. So this one is ok. I have the 1.6.1 version of torch geometric.

**Comment by nicolas-chaulet** [comment]
@humanpose1 should be good now.

**Review by humanpose1 — APPROVED** [review]
Nice

**Pull request merged**
