### PR TITLE
Fix to attribute error on not being able to access feature_dimension, num_classes etc.

### PR DESCRIPTION
**Pull request by diwakar-ravichandran**
This is the simple fix to the ongoing issue with the setattr not working. Since we are not getting past this point, I thought of sharing my fix to the attribute error so that we can focus on how to fix the setattr problem

### CODE REVIEW

**Review by nicolas-chaulet — APPROVED** [review]

**Comment by CCInc** [comment]
Hi @diwakar-ravichandran thanks for the PR!

If this issue is specific to the forward script, could you try adding the fix further upstream? Maybe here:

`    model = checkpoint.create_model(DictConfig(checkpoint.dataset_properties), weight_name=cfg.weight_name)`

and see if that works too?

**Comment by diwakar-ravichandran** [comment]
> Hi @diwakar-ravichandran thanks for the PR!
> 
> If this issue is specific to the forward script, could you try adding the fix further upstream? Maybe here:
> 
> ` model = checkpoint.create_model(DictConfig(checkpoint.dataset_properties), weight_name=cfg.weight_name)`
> 
> and see if that works too?

@CCInc Hi! I'll look into it!

**Comment by CCInc** [comment]
@diwakar-ravichandran have you had a chance to look into this? thanks!

**Comment by diwakar-ravichandran** [comment]
> @diwakar-ravichandran have you had a chance to look into this? thanks!

Heyy sorry I was caught up with some other work I haven't really had the chance to look at this.

**Pull request closed without merging**
