### PR TITLE
Bug ms svconv 

### PR DESCRIPTION
**Pull request by humanpose1**
because of Omegaconf, some models could not load on this colab [notebook](https://colab.research.google.com/github/humanpose1/MS-SVConv/blob/main/notebook/demo_MSSVConv.ipynb).

So, I correct it.

### CODE REVIEW

**Review by nicolas-chaulet — APPROVED** [review]

**Comment by nicolas-chaulet** [comment]
@humanpose1 there seems to be some trouble with linting, could you please double check? Otherwise looks great!

**Comment by humanpose1** [comment]
Thanks @nicolas-chaulet ! I don't understand why there is this problem of linting...
```
torch_points3d/datasets/registration/testplanetary.py:9: error: Library stubs not installed for "requests" (or incompatible with Python 3.6)
```
normally when we apply mypy we ignore missing imports...

**Comment by nicolas-chaulet** [comment]
Is it working on your local machine?

Le mar. 15 juin 2021 à 09:18, humanpose1 ***@***.***> a
écrit :

**Comment by humanpose1** [comment]
locally if I do:
```
mypy --ignore-missing-imports torch_points3d
```
mypy raises an error
```
torch_points3d/utils/wandb_utils.py:106: error: "None" has no attribute "dir"
Found 1 error in 1 file (checked 206 source files)
```
but it is not the same error of linting...

**Comment by humanpose1** [comment]
I think it comes from the version of mypy. I'm using 0.812 and we used to use vthat version too. Whereas github now seems to use the version 0.902. Maybe now mypy is stricter.

**Pull request merged**
